### ISSUE TITLE
0000910: Add support for params for annotations

### ISSUE THREAD

**Issue by sidler** [kajona/kajonacms#10]
The current annotation-handler should be extended by a method "getParamsForAnnotations", evaluating an annotation like 

@fieldType textarea [intBitLarge=true, intNumberOfRows=8]

to 
array(
  intBitLarge => true,
  intNumberOfRows => 8
)

This allows other classes like the formgenerator or validators to be parametrized

see http://board.kajona.de/viewtopic.php?f=27&t=1370

Updated syntax: we should keep to the java standards:
@test(param1=val1, param2=val2)

**Comment by sidler** [comment]
@spoonguard2k any updates?

**Comment by spoonguard2k** [comment]
implemented: Syntax is as follows:
test (param1=0, param2="abc", param3={"0", 123, 456}, param4=999, param5="hans im glück")
