### ISSUE TITLE
undeclared variables (errors in web console)

### ISSUE THREAD

**Issue by mrbashshell** [kajona/kajonacms#100]
some Kajona variables are not declared. see screenshots.

ReferenceError: assignment to undeclared variable KAJONA_LANGUAGE index.php:27:1
ReferenceError: assignment to undeclared variable KAJONA_WEBPATH index.php:27:25
ReferenceError: assignment to undeclared variable KAJONA_BROWSER_CACHEBUSTER index.php:27:75
ReferenceError: assignment to undeclared variable KAJONA_PHARMAP index.php:28:1

![bildschirmfoto 2016-05-10 um 08 58 13](https://cloud.githubusercontent.com/assets/7237752/15138017/71e1da6e-168d-11e6-9f34-f8a962a1befd.png)

**Comment by sidler** [comment]
@k42b3 , @spoonguard2k , are you able to reproduce this? I for myself can't generate those warnings.
