### ISSUE TITLE
Cannot download kajona_v5.0_allinone.zip

### ISSUE THREAD

**Issue by torsybil** [kajona/kajonacms#101]
**problem :** cannot download the [latest](https://www.kajona.de/en/Downloads/downloads.get_kajona.html) release of Kojana V5 

**reason for download :** LDAP login interface for users in [Kojana_v4.7](https://www.kajona.de/download.php?systemid=a98994c574608c13fb49) doesn't exist 

**workaround :** I tried to update from V4 to V5 using the steps [here](https://www.kajona.de/en/Documentation/V4-to-V5-Update/v4-to-v5-update.html) but produces an error that an update is only possible if you have at least kojana v4.7.1

**question :** First - why is my am I getting this message on executing v5preupdate.php?

```
Kajona V5 pre update sequence

Welcome to the V5 update helper.

This script backs up your v4 template and creates a new template pack out of it.


Error
Your Kajona-Installation is currently on version 4.7.2
You need at least version 4.7.1 to upgrade to 5.0
Aborting!

```

Second - why is [kajona_v5.0_allinone](https://www.kajona.de/en/Downloads/downloads.get_kajona.html) timing out on download?

**Comment by sidler** [comment]
Hi there!

it seems as the update-scripts didn't check the version properly. We fixed this, please download the script once more right here: https://raw.githubusercontent.com/kajona/v5preupdate/master/v5preupdate.php

Regarding the other issues - the download of V5.0 from kajona.de works as expected, do you still get timeouts?
The ldap package is available for both, v4.7 and v5.0, by the way.
