### ISSUE TITLE
Portaleditor

### ISSUE THREAD

**Issue by jaennert** [kajona/kajonacms#109]
Im Portaleditor lassen sich Objekte nicht bearbeiten, weil mit der Maus nicht auf die Edit-Symbole geklickt werden kann.
<img width="1041" alt="bildschirmfoto 2018-09-25 um 14 32 00" src="https://user-images.githubusercontent.com/43601730/46067429-160cb280-c177-11e8-92c6-f0e4d92ab5e8.png">
bzw. das Auswahlfeld verdeckt wird.
![bildschirmfoto 2018-09-25 um 14 34 05](https://user-images.githubusercontent.com/43601730/46067454-1f961a80-c177-11e8-8714-8f5ce4b0ea36.png)
Wo finde ich diese Elemente in der Administration?

**Comment by sidler** [comment]
Der Portaleditor wird leider häufig von Styles des Portal-Layouts beeinflusst.
Die Einstellungen sind aber vermutlich auch im Backend über die Master-Seite und die darauf enthaltenen Navigationselemente erreichbar.
