### ISSUE TITLE
0000940: Changelog Restorer not working properly

### ISSUE THREAD

**Issue by sidler** [kajona/kajonacms#21]
The method "restoreProperty" in "class class_module_system_changelog_restorer" does not work properly.

It searches the value for the given property correctly, but if no value for the given date and property was found it automatically assigns the latest for that property regardless of the given date.

**Comment by spoonguard2k** [comment]
Bug fixed:
If no value was found for a certain property then no longer the latest value of that property will be retrieved.

See commit 16e468e9ebce5053e480d0fb303ccca5a606184b
