### ISSUE TITLE
Backend Calendar: Refactor Calendar Sources

### ISSUE THREAD

**Issue by sidler** [kajona/kajonacms#29]
Currently the calendar-entries are generated using the corresponding admin-view-classes. This is rather senseless and creates too large admin controllers. The calendar-entry generation should be moved to separate objects implementing a special marker-interface.

**Comment by sidler** [comment]
@k42b3 this one is done, isn't it?

**Comment by k42b3** [comment]
Yes its done. We now have seperated provider classes which each module can provide. Afaik all modules are already moved to this new system so we could close this issue.
