### ISSUE TITLE
RfC / DevCon 2015: add support for phar based modules

### ISSUE THREAD

**Issue by sidler** [kajona/kajonacms#3]
In order to provide simplified updates, we should consider providing each module as a single phar file.
therefore we have to refactor two main parts:
- the resource-loader should be able to load contents from both, a packaged phar or a full filesystem based module
- the js files need to be deplyoed into a readable directory when serving contents from phars. otherwise all requests need to be handled by php. since nearly all js-files are loaded by the loader-script, this could be a possible solution.
- the detection of a re-deployment of static files could be based on a md5 / sha1 hash map: as soon as the hash-sum of a phar based package changes, the files should be redeployed

nevertheless, this needs a deep integration into the build process to swap paths and more

**Comment by phw** [comment]
It could be worth to see if [composer](https://getcomposer.org/) would solve some of the issues. It's similar to e.g. Node's npm or Ruby's gem and could definitely be used to install both Kajona's own dependencies and project specific dependencies, but maybe even Kajona modules which would cover what is proposed here.

**Comment by k42b3** [comment]
For composer it is possible to provide a custom installer, probably we can write our own composer installer (https://github.com/composer/installers) for Kajona.
