### ISSUE TITLE
Move form-generator / getAdminForm to external class

### ISSUE THREAD

**Issue by sidler** [kajona/kajonacms#42]
Currently, an objects' admin-form representation is generated by the corresponding view-controller.
This is rather against the design principles, since the form is view-based and the controller workflow based.
Therefore we should think about a new mapping of objects to admin-forms. A possible approach would be to move the logic to generate an form-generator instance out of an object to external classes, either mapped by a naming-convention or a class-based annotation.

Example:
```
@formCreator class_faq_form_generator
class class_module_faqs_faq { 
}
```

in class_admin_evensimpler, the new and edit actions have to be changed in order to instantiate the matching formCreator when editing or creating a new record.
In consequence, this decouples the admin-classes from the form-creators, making cross-module-edits way more comfortable.

**Comment by k42b3** [comment]
This is now implemented, a model can have an formGenerator annotation which is used by the getAdminForm method. In this way we can decouple the admin-classes from the form-creators
