### ISSUE TITLE
Add a new possibility to automatically update 1:n relations in an object

### ISSUE THREAD

**Issue by spoonguard2k** [kajona/kajonacms#46]
Like updating String or Integer properties of an object it would be great to have something similar for *1:n relations* without writing the SQL for updating the 1:n relation. Furthermore it should be possible to retrieve the related objects easily via the getter-methods (lazy loading) without writing the SQL-Code for that.

### Suggestion:
* For properties a new annotation e.g. ```@objectList <tablename>``` will be introduced,
* Properties with the annoation  ```@objectList ```  must be of type array,
* ```<tablename>``` ist the name of the table which contains the relation information,
* The defined table will automatically be created by it's installer (manual creation of the table is not needed). Each table contains two columns (source, traget) which contains the id's of the relation.

When an object is being saved, the all object in the array of the property will be updated automatically.
If an object is being retrieved form the database, the array will not be initialized. The array will be initialzed when calling the getter-Method of that property.

**Comment by k42b3** [comment]
it would be nice to have paramaetrized annotations to add the target and source col, e.g.
``` @objectListe tablename (source=col1,target=col2) ```

**Comment by k42b3** [comment]
regarding the autoload: maybe a proxy object could be feasible

**Comment by sidler** [comment]
As discussed: we should throw events in case of new / removed assignments

**Comment by sidler** [comment]
fixed with merge commit bc7d9937279cdf6b67359123c9671ba25fb32330
